# Generated by Django 5.2.8 on 2025-12-18 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('data_feed', 'Data feed'), ('terminal', 'Terminal'), ('analytics', 'Analytics'), ('index_license', 'Index license'), ('connectivity', 'Connectivity'), ('other', 'Other')], max_length=50)),
                ('service_code', models.CharField(blank=True, help_text='Vendor SKU / product code, if available.', max_length=100)),
                ('default_currency', models.CharField(blank=True, help_text='ISO currency code, e.g. USD, EUR, GBP.', max_length=3)),
                ('default_billing_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
            ],
            options={
                'ordering': ['vendor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(blank=True, choices=[('market_data', 'Market data'), ('reference_data', 'Reference data'), ('indexes', 'Indexes'), ('connectivity', 'Connectivity'), ('other', 'Other')], max_length=50)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for this vendor')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags (e.g. market data, EMEA, Tier1)', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('business_unit', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('default_approver', models.ForeignKey(blank=True, help_text='Default approver for spend / licenses on this cost center.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(help_text='Contract name or internal reference.', max_length=255)),
                ('contract_id', models.CharField(blank=True, help_text='Vendor contract ID / number, if applicable.', max_length=100)),
                ('contract_type', models.CharField(blank=True, choices=[('master', 'Master'), ('order_form', 'Order form'), ('amendment', 'Amendment'), ('other', 'Other')], max_length=50)),
                ('entity', models.CharField(blank=True, help_text='Legal entity / desk / cost centre.', max_length=255)),
                ('annual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total annual contract value in contract currency.', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency of the annual contract value, e.g. USD, EUR.', max_length=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Signed contract document', null=True, upload_to='contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL)),
                ('owning_cost_center', models.ForeignKey(blank=True, help_text='Which cost center owns this contract overall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='portal.costcenter')),
                ('related_services', models.ManyToManyField(blank=True, related_name='contracts', to='portal.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='portal.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(help_text='Invoice currency, e.g. USD, EUR.', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount as received on the invoice.', max_digits=14)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Tax / VAT amount (optional).', max_digits=14, null=True)),
                ('period_start', models.DateField(blank=True, help_text='Start date of the billed period, if applicable.', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date of the billed period, if applicable.', null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded PDF of the invoice.', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, help_text='If this invoice relates to a specific contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='portal.contract')),
                ('owner', models.ForeignKey(help_text='Which portal user this invoice belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='portal.vendor')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
                'unique_together': {('vendor', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description as it appears on the invoice.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, help_text='Price per unit in line currency.', max_digits=14, null=True)),
                ('line_amount', models.DecimalField(decimal_places=2, help_text='Total amount for this line.', max_digits=14)),
                ('currency', models.CharField(blank=True, help_text='Line currency if different from invoice currency.', max_length=3)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='portal.costcenter')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portal.invoice')),
                ('user', models.ForeignKey(blank=True, help_text='End user for personal licenses, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_invoice_lines', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='portal.service')),
            ],
            options={
                'ordering': ['invoice_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Override if different from first_name + last_name.', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Office / city / region.', max_length=255)),
                ('legal_entity', models.CharField(blank=True, help_text='Legal entity this user belongs to.', max_length=255)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='portal.costcenter')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager of this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portal.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('vendor', 'name')},
        ),
    ]
