# Generated by Django 5.2.8 on 2025-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_schema_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes / scope / renewal terms.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes to Finance / GL / tax.'),
        ),
    ]
