# Generated by Django 5.2.8 on 2025-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_service_allocation_split_service_list_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Work phone, extension or mobile.', max_length=50),
        ),
    ]
