# Generated by Django 5.2.8 on 2025-12-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='allocation_split',
        ),
        migrations.RemoveField(
            model_name='service',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner_display',
        ),
        migrations.RemoveField(
            model_name='service',
            name='primary_contract',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
