# Generated by Django 5.2.8 on 2025-12-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_service_allocation_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allocation_split',
            field=models.CharField(blank=True, help_text='High-level split, e.g. 60% Trading / 40% Research.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Indicative annual price or unit price for this service.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='owner_display',
            field=models.CharField(blank=True, help_text='Business owner / accountable person for this service.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='primary_contract',
            field=models.ForeignKey(blank=True, help_text='Primary contract under which this service is provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_services', to='portal.contract'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Work phone, extension or mobile.', max_length=50),
        ),
    ]
