# Generated by Django 5.2.8 on 2025-12-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_service_allocation_split_service_list_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notice_date',
            field=models.DateField(blank=True, help_text='Date by which notice must be given. If blank, it can be derived from end_date - notice_period_days.', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(30, '30 days'), (60, '60 days'), (90, '90 days'), (120, '120 days')], help_text='Notice period in days (e.g. 30/60/90/120). Used to calculate notice date.', null=True),
        ),
    ]
