# Generated by Django 5.2.8 on 2025-12-24 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auditevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='portal_audi_content_737802_idx',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditevent',
            name='content_type',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='object_type',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor_display',
            field=models.CharField(blank=True, help_text='Snapshot of actor name/email at the time of change.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id', '-occurred_at'], name='portal_audi_object__5712bf_idx'),
        ),
    ]
