# Generated by Django 5.2.8 on 2025-12-24 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_auditevent_portal_audi_content_737802_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditevent',
            name='portal_audi_object__5712bf_idx',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='action',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, help_text='Optional structured action for UI filtering (create/update/delete).', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id', 'occurred_at'], name='portal_audi_object__631057_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id'], name='portal_audi_object__349d36_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['occurred_at'], name='portal_audi_occurre_c563d9_idx'),
        ),
    ]
