# Generated by Django 5.2.8 on 2025-12-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_auditevent_portal_audi_object__5712bf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft status flag. True = Active, False = Closed (hidden unless Show Closed is enabled).'),
        ),
    ]
