# Generated by Django 5.2.8 on 2025-12-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft status flag. True = Active, False = Closed (hidden unless Show Closed is enabled).'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['vendor', 'is_active', 'name'], name='portal_serv_vendor__684cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='portal_serv_is_acti_0f3ef3_idx'),
        ),
    ]
