# Generated by Django 5.2.8 on 2025-12-24 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_service_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True = access granted; False = access revoked (kept for history).')),
                ('granted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text='Optional internal notes (e.g. desk / project / reason).', max_length=255)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who granted access (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_service_access', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Who revoked access (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_service_access', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='portal.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'user__username', 'service__vendor__name', 'service__name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='portal_user_user_id_5745b8_idx'), models.Index(fields=['service', 'is_active'], name='portal_user_service_acda9f_idx'), models.Index(fields=['is_active'], name='portal_user_is_acti_3df464_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'service'), name='uniq_user_service_access')],
            },
        ),
    ]
