# Generated by Django 5.2.8 on 2025-12-24 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_userserviceaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Actor who made the assignment (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='portal.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='UserServiceAccess',
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['service', 'user'], name='portal_serv_service_18ae89_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['user', 'service'], name='portal_serv_user_id_8d92ba_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceassignment',
            index=models.Index(fields=['assigned_at'], name='portal_serv_assigne_0f337f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceassignment',
            unique_together={('user', 'service')},
        ),
    ]
