# Generated by Django 5.2.8 on 2025-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, help_text='Where the lead came from (e.g. website, referral, conference).', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
