# Generated by Django 5.2.8 on 2025-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_contactrequest_options_contactrequest_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='persona',
            field=models.CharField(blank=True, choices=[('trading', 'Trading / dealing desks'), ('cfo', 'CFO / finance'), ('investor', 'Investor / board'), ('other', 'Other / not specified')], help_text='Primary persona this request belongs to.', max_length=20),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed / not a fit')], default='new', help_text='Internal status in your follow-up pipeline.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
